"""
为CreateCardModal添加自动提取标题功能
"""

# 读取文件
file_path = r'C:\test\antinet\src\components\CreateCardModal.tsx'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. 添加自动提取标题的函数（在组件内部，state定义之后）
auto_title_function = '''
  // 自动从内容提取标题
  const extractTitle = (content: string): string => {
    if (!content.trim()) return '';
    
    // 1. 尝试提取第一行作为标题
    const firstLine = content.split('\\n')[0].trim();
    if (firstLine && firstLine.length <= 50) {
      return firstLine;
    }
    
    // 2. 尝试提取第一个句子（以。！？.!?结尾）
    const sentenceMatch = content.match(/^[^。！？.!?]{5,50}[。！？.!?]?/);
    if (sentenceMatch) {
      return sentenceMatch[0].trim();
    }
    
    // 3. 提取前50个字符
    return content.substring(0, 50).trim() + (content.length > 50 ? '...' : '');
  };

  // 处理内容变化，自动更新标题
  const handleContentChange = (value: string) => {
    setFormData(prev => {
      // 如果标题为空或是自动生成的，则自动更新
      const isAutoGenerated = !prev.title || prev.title === extractTitle(prev.content);
      return {
        ...prev,
        content: value,
        title: isAutoGenerated ? extractTitle(value) : prev.title
      };
    });
  };
'''

# 查找 setFormData 或类似的状态定义
if 'const [formData, setFormData]' in content:
    print("找到 formData state")
    
    # 查找 setFormData 定义后的位置插入函数
    pattern = r'(const \[formData, setFormData\] = useState<CardFormData>\(\{[^}]+\}\))'
    
    import re
    match = re.search(pattern, content)
    if match:
        insert_pos = match.end()
        
        # 在 formData 定义后插入函数
        new_content = content[:insert_pos] + auto_title_function + content[insert_pos:]
        
        # 2. 修改 textarea 的 onChange 使用新的处理函数
        # 查找 content textarea
        old_textarea = '''onChange={(e) => setFormData({...formData, content: e.target.value})}'''
        new_textarea = '''onChange={(e) => handleContentChange(e.target.value)}'''
        
        if old_textarea in new_content:
            new_content = new_content.replace(old_textarea, new_textarea)
            print("✅ 已替换 textarea onChange")
        else:
            print("⚠️  未找到 textarea onChange")
        
        # 保存文件
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(new_content)
        
        print("✅ 自动提取标题功能已添加")
    else:
        print("❌ 未找到 formData 定义")
else:
    print("❌ 未找到 formData state")
