const fs = require('fs');
const c = fs.readFileSync('src/pages/Home.tsx', 'utf8');
const old = "['team-collaboration'].includes(activeTab)";
const newVal = "['pdf-analysis', 'ppt-analysis', 'excel-analysis', 'document-center', 'format-converter', 'report-automation'].includes(activeTab)";
const i1 = c.indexOf(old);
const i2 = c.indexOf(old, i1 + 1);
console.log('Found at', i1, 'and', i2);
const result = c.replace(old, newVal).replace(old, newVal);
fs.writeFileSync('src/pages/Home.tsx', result);
console.log('Done');